version: "3.2"
services:
  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379

  api:
    depends_on: [postgres, redis]
    image: node:8.11.3
    command: "npm run start:dev"
    working_dir: "/src"
    volumes:
      - .:/src
    ports:
      - 8888:8888


  worker-reviewer:
    container_name: worker-reviewer
    depends_on: [postgres, redis]
    image: node:8.11.3
    command: "npm run start:w1:dev"
    working_dir: "/src"
    volumes:
      - .:/src

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: src/docker/DB.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
