version: "3.2"
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]

  api:
    image: node:8.11.3
    command: "node -v"
    volumes:
      - ./src/js/api:/src

  db:
    container_name: db
    build:
      context: .
      dockerfile: src/docker/DB.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
